#!/bin/sh

if [ -z "$AOC_SESSION" ]; then
	echo "Session not found. Make sure to set AOC_SESSION env variable to session from adventofcode.com"
	exit 1
fi

echo "Loading input for $1/$2"

YEAR=$(printf "%04d" $1)
DAY=$(printf "%02d" $2)
mkdir -p $YEAR/$DAY
curl -b "session=$AOC_SESSION" https://adventofcode.com/$1/day/$2/input > $YEAR/$DAY/input.txt
