#!/bin/sh

if [ -z "$AOC_SESSION" ]; then
	echo "Session not found. Make sure to set AOC_SESSION env variable to session from adventofcode.com"
	exit 1
fi

echo "Loading AOC problem for $1/$2"

YEAR=$(printf "%04d" $1)
DAY=$(printf "%02d" $2)
mkdir -p $YEAR/$DAY
echo "Original link: https://adventofcode.com/$YEAR/day/$DAY\n" > $YEAR/$DAY/readme.txt

curl -b "session=$AOC_SESSION" https://adventofcode.com/$YEAR/day/$DAY | sed -n "/<article class=\"day-desc\">/,/<\/article>/p" | sed -n '/^$/!{s/<p[^>]*>/|/g;p;}' | tr '|' '\n' | sed -n '/^$/!{s/<[^>]*>//g;p;}' >> $YEAR/$DAY/readme.txt

scripts/load_input $1 $2
